# Generated by Django 5.1.6 on 2025-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='email',
            field=models.EmailField(default='muhammad@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myusers',
            name='fullName',
            field=models.CharField(default='amir', max_length=100),
            preserve_default=False,
        ),
    ]
