# Generated by Django 5.1.6 on 2025-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myusers_email_myusers_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='Userpassword',
            field=models.CharField(default='12345678', max_length=100),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(default='amir@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='fullName',
            field=models.CharField(default='Amir', max_length=100),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='username',
            field=models.CharField(default='Amir', max_length=100),
        ),
    ]
