# Generated by Django 5.1.6 on 2025-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myusers_userpassword_alter_myusers_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='email',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='Userpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
