# Generated by Django 5.1.6 on 2025-02-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_myusers_email_alter_myusers_userpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myusers',
            old_name='Userpassword',
            new_name='userPassword',
        ),
    ]
