# Generated by Django 5.1.6 on 2025-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_delete_myusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
