# Generated by Django 5.1.6 on 2025-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
