# Generated by Django 5.1.6 on 2025-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_myusers_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='verify',
            field=models.BooleanField(),
        ),
    ]
