# Generated by Django 5.1.7 on 2025-05-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_trees', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
