# Generated by Django 5.1.7 on 2025-06-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palm_trees', '0003_register_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='verify',
            new_name='verified',
        ),
    ]
