# Generated by Django 4.2.21 on 2025-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm_trees', '0004_rename_verify_register_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=10),
        ),
    ]
