# Generated by Django 5.1.6 on 2025-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('referral_code', models.CharField(default='cd211a69f3', max_length=10)),
                ('referred_by', models.CharField(max_length=100)),
                ('referred_users', models.CharField(max_length=100)),
            ],
        ),
    ]
