# Generated by Django 5.1.6 on 2025-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarCoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_code',
            field=models.CharField(default='25846d0845', max_length=10),
        ),
    ]
