# Generated by Django 5.1.6 on 2025-03-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarCoin', '0002_alter_myusers_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_code',
            field=models.CharField(default='4f924285ed', max_length=10),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='referred_by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='referred_users',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
