# Generated by Django 5.1.6 on 2025-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarCoin', '0003_alter_myusers_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_code',
            field=models.CharField(default='ac69d77f5d', max_length=10),
        ),
    ]
