# Generated by Django 5.1.6 on 2025-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarCoin', '0004_alter_myusers_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_code',
            field=models.CharField(default='a10315fbdc', max_length=10),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='referred_by',
            field=models.CharField(default=[], max_length=100),
        ),
    ]
