# Generated by Django 5.1.6 on 2025-03-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarCoin', '0006_alter_myusers_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_code',
            field=models.CharField(default='356959d03b', max_length=10),
        ),
    ]
