# Generated by Django 5.1.6 on 2025-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarCoin', '0008_alter_myusers_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='referral_code',
            field=models.CharField(default='9f047fe3cb', max_length=10),
        ),
    ]
